name       : createrepo_c
version    : 0.11.1
release    : 5
source     :
    - https://github.com/rpm-software-management/createrepo_c/archive/0.11.1.tar.gz : 6c8294dfef38ac78fad2efce01ea7a993e743e7ddfb53215ae7d65abe5e21e48
license    : GPL-2.0-or-later
summary    : C implementation of the createrepo.
component  : programming.devel
description: |
    C implementation of the createrepo.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - pkgconfig(popt)
    - pkgconfig(rpm)
    - bzip2-devel
setup      : |
    %cmake . -DENABLE_PYTHON=OFF
build      : |
    %make
install    : |
    %make_install
