name       : createrepo_c
version    : 0.1.14
release    : 1
source     :
    - https://fedorahosted.org/releases/c/r/createrepo_c/createrepo_c-0.1.14.tar.xz : a3f545d45575ba5a70f68b174354dd6e6df096e30f2cab24bbe98b36d0f6527f
license    : GPL-2.0
summary    : C implementation of the createrepo.
description: |
    C implementation of the createrepo.
clang      : no
builddeps  :
    - pkgconfig(sqlite3)
    - pkgconfig(rpm)
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-broken-prefix-usage.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
